#+TITLE: sacre bileşen çerçevesi

* sacre bileşen çerçevesi

sacre ([[https://github.com/derino/sacre]]), bileşen tabanlı bir duraksız veri işleme çerçevesidir. Açık kaynaklı bir yazılımdır. 
sacre bileşen çerçevesi ile uygulama geliştirmek iki adımdan oluşuyor.

+ iş hattı oluşturmak

 İş hattı oluşturmak bileşenleri dizerek uygulama oluşturmak isteyen kullanıcıların nasıl yapıldığını bilmesi gereken bir faaliyettir.

+ bileşen tanımlamak

 Yeni bileşen yaratmak belirli bir uygulama alanı için uygulama geliştirilebilmesini sağlamak için yapılır. Geliştiricilere yönelik bir faaliyettir. 
 

* İş hattı oluşturmak
sacre'de bileşenler iş parçacığı olarak çalışırlar ve kapılarına bağlı diğer bileşenlerle belirli tipteki verileri alıp vererek iletişirler. Hangi bileşenlerin birbiriyle hangi kapıları üzerinden bağlı olduğunu tanımlayan dizilime /iş hattı/ denir. sacre'de iş hattı oluşturmak için basit bir dil var. En basit haliyle bileşenler birbirlerine ~!~ işlemiyle seri, ~&~ işlemiyle paralel bağlanıyor. ~&~ işleminin ~!~ işlemine göre önceliği var. Dikkat edilmesi gereken nokta birbirine bağlanan kapıların aynı veri tipini geçiriyor olmalarıdır.

#+BEGIN_SRC ditaa :file imgs/ornek-is-hatti.png :cmdline -r -s 0.8
+-----+                             +-----+
|     |                             |     |   --> giriş kapısı
|  A  |>-+                       +--+> E  |   
|     |  |                       |  |     |   >-- çıkış kapısı
+-----+  |  +-----+     +-----+  |  +-----+
         +--+>    |     |     |>-+            --- bağlayıcı
            |  C  |>----+> D  | 
         +--+>    |     |     |>-+
+-----+  |  +-----+     +-----+  |  +-----+
|     |  |                       |  |     |
|  B  |>-+                       +--+> F  |
|     |                             |     |
+-----+                             +-----+
#+END_SRC


Üstteki resimde görülen örnek iş hattını tanımlamak için ~A & B ! C ! D ! E & F~ ifadesi yeterli.

* Öz sacre bileşenleri
Uygulamaya özgü tanımlanmış bileşenlerin dışında sacre'nin kendiliğinden gelen bazı bileşenleri de var:
- [[file:SsgppComps.org::*apisink][apisink]] 
- [[file:SsgppComps.org::*fork1xn][fork1xn]]
- [[file:SsgppComps.org::*mergenx1][mergenx1]]
- [[file:SsgppComps.org::*intersection][intersection]]
- [[file:SsgppComps.org::*gnd][gnd (ground)]]
- [[file:SsgppComps.org::*limitflt][limitflt]]

* Bileşen tanımlamak

sacre için yeni bileşenler tanımlamak için ~ch.alari.sacre.Component~ sınıfından yeni bir bileşen sınıfı türetmek yeterlidir. 
sacre açık kaynaklı bir proje olduğu için halihazırda tanımlanmış sacre bileşenlerinin kodlarını inceleyerek nasıl yapıldığını daha iyi görebilirsiniz.
ssg++ için bileşenler çalışma zamanında yüklenecek şekilde eklenti olarak tanımlanabilir (bkz: [[file:SsgppIcinEklentiBilesenTanimlamak.org][ssg++ için eklenti bileşen tanımlamak]]). 
ssg++'da tanımlanmış bileşenleri görmek için (bkz: [[file:SsgppComps.org][ssg++ bileşenleri]]).
