#+TITLE: ssg++ için eklenti bileşen tanımlamak
#+OPTIONS: toc:nil

* ssg++ için eklenti bileşen tanımlamak

ssg++'nın işlevselliğini kendi bileşenlerinizi kodlayarak da artırabilirsiniz. 

Örnek olarak [[https://github.com/ssgpp/eklentiler]] adresinde yer alan ssg++ bileşen havuzundaki kodlara bakabilirsiniz. 

~$ git checkout https://github.com/ssgpp/eklentiler.git~ ile =~/eklentiler= dizinine kodları aldığınızı varsayalım (~ işareti ev dizinini temsil ediyor. Linux altında örn. ~/home/user~). =~/.ssgpp/conf/app.properties= dosyasındaki ~EklentiDizini~ parametresini buna göre düzenleyin.

~EklentiDizini=~/eklentiler/~

Eklentiler klasörünün içinde derlenmiş eklenti bileşenlerinin bulunduğu ~jars~ klasörü, eklentilerin kaynak kodlarını içeren ~src~ klasörü ve eklentiler hakkında tanımlama bilgilerini içeren ~plugins.info~ dosyası bulunur. ~plugins.info~ dosyası satır satır eklentileri tanımlar. İki nokta üst üste karakteriyle ayrılan iki alanın ilkinde bileşenin iş hatlarında hangi adla kullanılacağını belirlenir. İkinci alan ise Eklenti sınıfının paketler içindeki tam adıdır. Örn.

~ÖrnekEklentiBileşen: sacre.plugins.comps.OrnekEklentiBilesen~

~src~ klasörü altında her bir eklenti bileşenin kaynak kodlarını içeren kendi klasörü bulunur. ~src/ornekeklentibilesen~ klasörüne örnek bileşen kodunun derlenmesi ve jar dosyasının oluşturulmasını sağlayan ~Makefile~ dosyası da dahil edilmiştir.

[[https://github.com/ssgpp/eklentiler/raw/master/src/ornekeklentibilesen/Makefile][Makefile]]
#+BEGIN_HTML
<script src="http://gist-it.appspot.com/github/ssgpp/eklentiler/blob/master/src/ornekeklentibilesen/Makefile?footer=no"></script>
#+END_HTML


~OrnekEklentiBilesen~ sınıfı şu şekilde tanımlanmıştır.

[[https://github.com/ssgpp/eklentiler/raw/master/src/ornekeklentibilesen/sacre/plugins/comps/OrnekEklentiBilesen.java][OrnekEklentiBilesen.java]]
#+BEGIN_HTML
<script src="http://gist-it.appspot.com/github/ssgpp/eklentiler/blob/master/src/ornekeklentibilesen/sacre/plugins/comps/OrnekEklentiBilesen.java?footer=no"></script>
#+END_HTML

~make~ kullanılarak ~ornekeklentibilesen.jar~ dosyası ~jars~ klasörü altında oluşturulduktan sonra ~örnekeklentibileşen~ ssg++ komut satırında bir iş hattı içerisinde kullanılabilir hale gelmiş olur. 
örn.: ~badiknk ! örnekeklentibileşen ! metinbtk~ 
